// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHCaaAzQs80IdR16HRAXg5OSZsTDr0WbQ',
    appId: '1:90238812754:web:7f8ca5685070bb49bc158b',
    messagingSenderId: '90238812754',
    projectId: 'beastmode-36db7',
    authDomain: 'beastmode-36db7.firebaseapp.com',
    storageBucket: 'beastmode-36db7.firebasestorage.app',
    measurementId: 'G-2YK8SGD650',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqCKZTxE4nxiEFNmDf-q-SJVV7uXoxGkU',
    appId: '1:90238812754:android:be9cbc90c1c8c022bc158b',
    messagingSenderId: '90238812754',
    projectId: 'beastmode-36db7',
    storageBucket: 'beastmode-36db7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy7LskHJtgKcaDsqvS0-OeiWbLx1i1dV8',
    appId: '1:90238812754:ios:5414911f7622808bbc158b',
    messagingSenderId: '90238812754',
    projectId: 'beastmode-36db7',
    storageBucket: 'beastmode-36db7.firebasestorage.app',
    iosBundleId: 'com.example.beastMode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy7LskHJtgKcaDsqvS0-OeiWbLx1i1dV8',
    appId: '1:90238812754:ios:5414911f7622808bbc158b',
    messagingSenderId: '90238812754',
    projectId: 'beastmode-36db7',
    storageBucket: 'beastmode-36db7.firebasestorage.app',
    iosBundleId: 'com.example.beastMode',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHCaaAzQs80IdR16HRAXg5OSZsTDr0WbQ',
    appId: '1:90238812754:web:32c91b6095c7440dbc158b',
    messagingSenderId: '90238812754',
    projectId: 'beastmode-36db7',
    authDomain: 'beastmode-36db7.firebaseapp.com',
    storageBucket: 'beastmode-36db7.firebasestorage.app',
    measurementId: 'G-NFKWJ5D2EE',
  );
}
